version: "3.2"
services:

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    environment:
     - REDIS_REPLICATION_MODE=master
     - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - code-network

  notification-service:  
    image: notification-service
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    depends_on:
      - redis
    restart: always
    networks:
      - code-network

  test-generator:  
    image: test-generator
    build:
      context: ./test-generator
      dockerfile: Dockerfile
    depends_on:
      - redis
    restart: always
    networks:
      - code-network

  test-client:  
    image: test-client
    build:
      context: ./test-client
      dockerfile: Dockerfile
    depends_on:
      - notification-service
    restart: always
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
